version: '3'

services:
  http:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html  # Ajout du volume partagé directement
    networks:
      - reseau
    depends_on:
      - script

  script:
    build: .
    networks:
      - reseau
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - data

  data:
    image: mariadb:10.2
    networks:
      - reseau
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./data/:/var/lib/mysql

networks:
  reseau:
